/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_jacquet80_rds_input_V4LTunerGroupReader */

#ifndef _Included_eu_jacquet80_rds_input_V4LTunerGroupReader
#define _Included_eu_jacquet80_rds_input_V4LTunerGroupReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    isStereo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_isStereo
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    setFrequency
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_setFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    getFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_getFrequency
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    mute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_mute
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    unmute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_unmute
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    getSignalStrength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_getSignalStrength
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    hwSeek
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_hwSeek
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_close
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    hasRDS
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_hasRDS
  (JNIEnv *, jobject);

/*
 * Class:     eu_jacquet80_rds_input_V4LTunerGroupReader
 * Method:    getRDSData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_eu_jacquet80_rds_input_V4LTunerGroupReader_getRDSData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
