FLAGS=-Wall -W -Wfatal-errors -wunused -pedantic -std=gnu99 `pkg-config libusb-1.0 --cflags` -fPIC
LINKFLAGS=`pkg-config librtlsdr --libs` -framework IOKit -framework CoreFoundation

all: rtl_plugin

rtl_plugin: eu_jacquet80_rds_input_NativeTunerGroupReader.h rtl_plugin.c convenience/convenience.c
	gcc -shared -o rtl.dylib rtl_plugin.c convenience/convenience.c kissfft/kiss_fft.c kissfft/kiss_fftr.c -I /System/Library/Frameworks/JavaVM.framework/Headers $(FLAGS) $(LINKFLAGS)
	