FLAGS=-Wall -W -Wfatal-errors -pedantic -std=gnu99 `pkg-config libusb-1.0 --cflags` -fPIC
LINKFLAGS=`pkg-config librtlsdr --libs` -lrt -lpthread

all: rtl_plugin

rtl_plugin: eu_jacquet80_rds_input_NativeTunerGroupReader.h rtl_plugin.c convenience/convenience.c
	gcc -shared -o rtl.so rtl_plugin.c convenience/convenience.c kissfft/kiss_fft.c kissfft/kiss_fftr.c -I /usr/lib/jvm/default-java/include -I /usr/lib/jvm/default-java/include/linux $(FLAGS) $(LINKFLAGS)
